[package]
name = "axum-htpasswd"
version = "0.1.0"
edition = "2021"

authors = ["Sebastian Schäfer <sarek@uliweb.de>"]
description = "Simple file-based authentication in Axum"
homepage = "https://github.com/Sarek/axum-htpasswd"
repository = "https://github.com/Sarek/axum-htpasswd"
license = "MIT"
categories = ["web-programming"]

[dependencies]
